name: Build and Package DEB

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential:native python3-all debhelper dh-python fakeroot
          pip install --upgrade pip
          pip install stdeb wheel setuptools

      - name: Build DEB package
        run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          python setup.py --command-packages=stdeb.command bdist_deb

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-usage-timer-deb
          path: deb_dist/*.deb
